### ISSUE TITLE
Documentation needed about how to clone the site

### ISSUE THREAD

**Issue by parijke** [DrupalNL/drupal-in-a-day-website#2]
Like using drupal-scaffold instead of composer install

**Comment by dbazuin** [comment]
I think drupal scaffold should run when you do a composer install, maybe there is something wrong in the composer.json.

**Comment by parijke** [comment]
Sean can you clearify this?

**Comment by seanBlommaert** [comment]
Will update the readme file on how to install etc.

**Comment by parijke** [comment]
That would be great!

**Comment by parijke** [comment]
Also about the usage of the split config if possible

**Comment by seanBlommaert** [comment]
Done!
