### ISSUE TITLE
Configuration Import fails

### ISSUE THREAD

**Issue by parijke** [DrupalNL/drupal-in-a-day-website#3]
After installing and importing the database, the command drush cim fails:

The configuration cannot be imported because it failed validation for the following reasons:
Unable to install the minimal module since it does not exist.

**Comment by dbazuin** [comment]
Ik kon wel exporteren en daarna is het lokaal hier gefixed.
Ik heb dit gepushed, kun je een pull doen en het nog eens proberen?

**Comment by parijke** [comment]
Doe ik vanavond

**Comment by parijke** [comment]
Confirmed.... there are no changes to import (no errors)
